import type { NextPage } from 'next'
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {ChangeEvent, useState, useMemo} from "react";

/**
 * @define the response type from Pokemon api
 */
interface Pokemon {
  id: number;
  name: string;
  image: string;
}

/**
 * @define using getServerSideProps to get the pokemon list from server
 */
export async function getServerSideProps() {
  const response = await fetch(`https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json`);
  return {
    props: {
      pokemons: await response.json()
    }
  };
}


const Home: NextPage<{pokemons: Pokemon[]}> = ({pokemons}) => {

  // define the input statement in client side
  const [filter, setFilter] = useState('');

  // get the filtered pokemons by dependencies
  const filteredPokemons = useMemo(
    () => pokemons.filter((p: Pokemon) => p.name.toLowerCase().includes(filter.toLowerCase())),
    [filter, pokemons]);

  return (
    <div className={styles.main}>
      <Head>
        <title>Pokemon</title>
        <meta name={'description'} content={'generated by next.js'} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <input type="text" value={filter} onChange={(e: ChangeEvent<HTMLInputElement>) => setFilter(e.target.value)} />
      </div>
      <div className={styles.container}>
        {
          // render the filtered pokemon list on page
          filteredPokemons.slice(0, 20).map((p: Pokemon) => (
            <div key={p.id} className={styles.image}>
              <img src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${p.image}`} alt={p.name} />
              <h2>{p.name}</h2>
            </div>
          ))
        }
      </div>
    </div>
  )
}

export default Home
